/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XbelakeAmbulanceWlList {
    }
}
declare global {
    interface HTMLXbelakeAmbulanceWlListElement extends Components.XbelakeAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXbelakeAmbulanceWlListElement: {
        prototype: HTMLXbelakeAmbulanceWlListElement;
        new (): HTMLXbelakeAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xbelake-ambulance-wl-list": HTMLXbelakeAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XbelakeAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xbelake-ambulance-wl-list": XbelakeAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xbelake-ambulance-wl-list": LocalJSX.XbelakeAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXbelakeAmbulanceWlListElement>;
        }
    }
}
